name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username quantinium3 --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . --file Dockerfile --tag coderunner:$(date +%s)

    - name: push to ghcr
      run: docker push ghcr.io/quantinium3/coderunner:$(date +%s)
